//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<provision_marker_dss> provision_marker_dss { get; set; }
        public virtual DbSet<schema_info_dss> schema_info_dss { get; set; }
        public virtual DbSet<scope_config_dss> scope_config_dss { get; set; }
        public virtual DbSet<scope_info_dss> scope_info_dss { get; set; }
        public virtual DbSet<tb_announce_lang> tb_announce_lang { get; set; }
        public virtual DbSet<tb_announce_region> tb_announce_region { get; set; }
        public virtual DbSet<tb_blog> tb_blog { get; set; }
        public virtual DbSet<tb_blog_lang> tb_blog_lang { get; set; }
        public virtual DbSet<tb_blog_region> tb_blog_region { get; set; }
        public virtual DbSet<tb_brand_lang> tb_brand_lang { get; set; }
        public virtual DbSet<tb_catg_extra_lang> tb_catg_extra_lang { get; set; }
        public virtual DbSet<tb_catg_lang> tb_catg_lang { get; set; }
        public virtual DbSet<tb_catg_link> tb_catg_link { get; set; }
        public virtual DbSet<tb_cdp_mapper> tb_cdp_mapper { get; set; }
        public virtual DbSet<tb_country_lang> tb_country_lang { get; set; }
        public virtual DbSet<tb_curr> tb_curr { get; set; }
        public virtual DbSet<tb_discount> tb_discount { get; set; }
        public virtual DbSet<tb_discount_code> tb_discount_code { get; set; }
        public virtual DbSet<tb_discount_email> tb_discount_email { get; set; }
        public virtual DbSet<tb_discount_filter> tb_discount_filter { get; set; }
        public virtual DbSet<tb_discount_gift> tb_discount_gift { get; set; }
        public virtual DbSet<tb_discount_lang> tb_discount_lang { get; set; }
        public virtual DbSet<tb_discount_price> tb_discount_price { get; set; }
        public virtual DbSet<tb_discount_prod> tb_discount_prod { get; set; }
        public virtual DbSet<tb_id> tb_id { get; set; }
        public virtual DbSet<tb_lang> tb_lang { get; set; }
        public virtual DbSet<tb_line_lang> tb_line_lang { get; set; }
        public virtual DbSet<tb_log> tb_log { get; set; }
        public virtual DbSet<tb_member> tb_member { get; set; }
        public virtual DbSet<tb_member_address> tb_member_address { get; set; }
        public virtual DbSet<tb_member_basket> tb_member_basket { get; set; }
        public virtual DbSet<tb_member_favorite> tb_member_favorite { get; set; }
        public virtual DbSet<tb_member_wishlist> tb_member_wishlist { get; set; }
        public virtual DbSet<tb_news_lang> tb_news_lang { get; set; }
        public virtual DbSet<tb_news_region> tb_news_region { get; set; }
        public virtual DbSet<tb_partner> tb_partner { get; set; }
        public virtual DbSet<tb_prod> tb_prod { get; set; }
        public virtual DbSet<tb_prod_details_lang> tb_prod_details_lang { get; set; }
        public virtual DbSet<tb_prod_extra> tb_prod_extra { get; set; }
        public virtual DbSet<tb_prod_extra_lang> tb_prod_extra_lang { get; set; }
        public virtual DbSet<tb_prod_lang> tb_prod_lang { get; set; }
        public virtual DbSet<tb_prod_live_lang> tb_prod_live_lang { get; set; }
        public virtual DbSet<tb_prod_live_search_lang> tb_prod_live_search_lang { get; set; }
        public virtual DbSet<tb_prod_price> tb_prod_price { get; set; }
        public virtual DbSet<tb_prod_qty> tb_prod_qty { get; set; }
        public virtual DbSet<tb_prod_region> tb_prod_region { get; set; }
        public virtual DbSet<tb_promo> tb_promo { get; set; }
        public virtual DbSet<tb_promo_banner> tb_promo_banner { get; set; }
        public virtual DbSet<tb_promo_discount> tb_promo_discount { get; set; }
        public virtual DbSet<tb_promo_display> tb_promo_display { get; set; }
        public virtual DbSet<tb_promo_filter> tb_promo_filter { get; set; }
        public virtual DbSet<tb_promo_lang> tb_promo_lang { get; set; }
        public virtual DbSet<tb_promo_prod> tb_promo_prod { get; set; }
        public virtual DbSet<tb_region> tb_region { get; set; }
        public virtual DbSet<tb_region_link> tb_region_link { get; set; }
        public virtual DbSet<tb_review> tb_review { get; set; }
        public virtual DbSet<tb_shipment> tb_shipment { get; set; }
        public virtual DbSet<tb_shipment_lang> tb_shipment_lang { get; set; }
        public virtual DbSet<tb_shipment_price> tb_shipment_price { get; set; }
        public virtual DbSet<tb_shipment_state_lang> tb_shipment_state_lang { get; set; }
        public virtual DbSet<tb_so> tb_so { get; set; }
        public virtual DbSet<tb_so_hold_qty> tb_so_hold_qty { get; set; }
        public virtual DbSet<tb_so_info> tb_so_info { get; set; }
        public virtual DbSet<tb_so_line> tb_so_line { get; set; }
        public virtual DbSet<tb_so_pay> tb_so_pay { get; set; }
        public virtual DbSet<tb_so_prod> tb_so_prod { get; set; }
        public virtual DbSet<tb_so_prod_disc> tb_so_prod_disc { get; set; }
        public virtual DbSet<tb_so_refund> tb_so_refund { get; set; }
        public virtual DbSet<tb_so_reship> tb_so_reship { get; set; }
        public virtual DbSet<tb_so_reship_prod> tb_so_reship_prod { get; set; }
        public virtual DbSet<tb_so_return> tb_so_return { get; set; }
        public virtual DbSet<tb_so_return_prod> tb_so_return_prod { get; set; }
        public virtual DbSet<tb_so_shipment> tb_so_shipment { get; set; }
        public virtual DbSet<tb_subscribe> tb_subscribe { get; set; }
        public virtual DbSet<tb_tax> tb_tax { get; set; }
        public virtual DbSet<temp_pay_table> temp_pay_table { get; set; }
        public virtual DbSet<tb_prod_bundle> tb_prod_bundle { get; set; }
        public virtual DbSet<tb_promo_discount_lang> tb_promo_discount_lang { get; set; }
    }
}
