//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_announce_lang
    {
        public decimal announce_id { get; set; }
        public string lang_id { get; set; }
        public string announce_title_lang { get; set; }
        public string announce_msg_lang { get; set; }
        public System.DateTime announce_date { get; set; }
        public bool enable { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime update_date { get; set; }
    }
}
