//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cdp_mapper
    {
        public string field_type { get; set; }
        public string code { get; set; }
        public string field_value { get; set; }
        public string optional { get; set; }
        public string additional { get; set; }
    }
}
