//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_discount
    {
        public decimal disc_id { get; set; }
        public string disc_name { get; set; }
        public decimal rate { get; set; }
        public string remark { get; set; }
        public bool enable { get; set; }
        public System.DateTime from_date { get; set; }
        public System.DateTime to_date { get; set; }
        public System.DateTime update_date { get; set; }
        public System.DateTime create_date { get; set; }
    }
}
