//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_discount_filter
    {
        public decimal disc_id { get; set; }
        public string disc_filter { get; set; }
        public string filter_value { get; set; }
        public short qty { get; set; }
        public string curr_id { get; set; }
        public decimal min_price { get; set; }
        public bool filter { get; set; }
    }
}
