//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_log
    {
        public int log_id { get; set; }
        public string log_type { get; set; }
        public string region_id { get; set; }
        public string source { get; set; }
        public string filter { get; set; }
        public System.DateTime log_date { get; set; }
        public string log_msg { get; set; }
    }
}
