//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_member
    {
        public decimal member_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string region_id { get; set; }
        public string lang_id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string region_name { get; set; }
        public bool newsletter { get; set; }
        public string status { get; set; }
        public string facebook_id { get; set; }
        public string facebook_name { get; set; }
        public string create_ip { get; set; }
        public System.DateTime create_date { get; set; }
        public string login_ip { get; set; }
        public System.DateTime login_date { get; set; }
        public System.DateTime update_date { get; set; }
    }
}
