//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_member_favorite
    {
        public decimal member_id { get; set; }
        public string fav_brand1 { get; set; }
        public string fav_brand2 { get; set; }
        public string fav_brand3 { get; set; }
        public string skin_type { get; set; }
    }
}
