//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_member_address
    {
        public decimal address_id { get; set; }
        public decimal member_id { get; set; }
        public string address_name { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postal_code { get; set; }
        public string company { get; set; }
        public string address_1 { get; set; }
        public string address_2 { get; set; }
        public string address_3 { get; set; }
        public string mobile { get; set; }
        public string tel { get; set; }
        public bool is_default { get; set; }
        public string lang_id { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime update_date { get; set; }
    }
}
