//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_partner
    {
        public short partner_id { get; set; }
        public string partner_name { get; set; }
        public string partner_src { get; set; }
        public string partner_key { get; set; }
        public string email { get; set; }
        public string partner_ip { get; set; }
        public string region_id { get; set; }
        public string curr_id { get; set; }
        public string lang_id { get; set; }
        public System.DateTime create_date { get; set; }
    }
}
