//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_prod_bundle
    {
        public int bundle_prod_id { get; set; }
        public int prod_id { get; set; }
        public string region_id { get; set; }
        public short qty { get; set; }
        public string curr_id { get; set; }
        public decimal sell_price { get; set; }
        public decimal ref_price { get; set; }
    }
}
