//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_prod
    {
        public int prod_id { get; set; }
        public decimal catg_id { get; set; }
        public string brand_id { get; set; }
        public int group_id { get; set; }
        public string line_id { get; set; }
        public string size { get; set; }
        public string color { get; set; }
        public string color_name { get; set; }
        public decimal sell_price { get; set; }
        public decimal ref_price { get; set; }
        public string sku { get; set; }
        public string ship_type { get; set; }
        public bool enable { get; set; }
        public bool in_stock { get; set; }
    }
}
