//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_prod_details_lang
    {
        public int prod_id { get; set; }
        public string lang_id { get; set; }
        public string prod_lang_desc { get; set; }
        public string prod_lang_use { get; set; }
        public string prod_lang_ing { get; set; }
    }
}
