//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_review
    {
        public decimal review_id { get; set; }
        public int prod_id { get; set; }
        public decimal member_id { get; set; }
        public string region_id { get; set; }
        public string lang_id { get; set; }
        public string review_title { get; set; }
        public string review_content { get; set; }
        public byte rating { get; set; }
        public Nullable<bool> approval { get; set; }
        public short user_id { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime update_date { get; set; }
    }
}
