//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_so_shipment
    {
        public decimal so_id { get; set; }
        public string tracking_no { get; set; }
        public string shipment_type { get; set; }
        public System.DateTime dispatch_date { get; set; }
        public System.DateTime scanned_date { get; set; }
        public System.DateTime upload_date { get; set; }
    }
}
