//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_so_prod
    {
        public decimal so_id { get; set; }
        public int prod_id { get; set; }
        public string brand_name { get; set; }
        public string prod_name { get; set; }
        public string color_name { get; set; }
        public string size { get; set; }
        public decimal sell_price { get; set; }
        public short qty { get; set; }
        public short fullfill_qty { get; set; }
        public string ship_type { get; set; }
        public string shipment_id { get; set; }
        public int promo_id { get; set; }
    }
}
