//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_shipment_state_lang
    {
        public string country_id { get; set; }
        public string lang_id { get; set; }
        public string state_id { get; set; }
        public string state_name { get; set; }
        public string state_lang_name { get; set; }
    }
}
