//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_so
    {
        public decimal so_id { get; set; }
        public decimal member_id { get; set; }
        public string email { get; set; }
        public System.DateTime order_date { get; set; }
        public byte order_status { get; set; }
        public string bill_first_name { get; set; }
        public string bill_last_name { get; set; }
        public string bill_country { get; set; }
        public string bill_country_id { get; set; }
        public string bill_city { get; set; }
        public string bill_state { get; set; }
        public string bill_company { get; set; }
        public string bill_address_1 { get; set; }
        public string bill_address_2 { get; set; }
        public string bill_address_3 { get; set; }
        public string bill_postal_code { get; set; }
        public string bill_mobile { get; set; }
        public string bill_tel { get; set; }
        public string ship_first_name { get; set; }
        public string ship_last_name { get; set; }
        public string ship_country { get; set; }
        public string ship_country_id { get; set; }
        public string ship_city { get; set; }
        public string ship_state { get; set; }
        public string ship_company { get; set; }
        public string ship_address_1 { get; set; }
        public string ship_address_2 { get; set; }
        public string ship_address_3 { get; set; }
        public string ship_postal_code { get; set; }
        public string ship_mobile { get; set; }
        public string ship_tel { get; set; }
        public string lang_id { get; set; }
        public string region_id { get; set; }
        public string curr_id { get; set; }
        public decimal rate { get; set; }
    }
}
