//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_shipment_price
    {
        public string shipment_id { get; set; }
        public string country_id { get; set; }
        public string ship_type { get; set; }
        public string curr_id { get; set; }
        public decimal min_amount { get; set; }
        public decimal max_amount { get; set; }
        public decimal price { get; set; }
        public short weight { get; set; }
    }
}
