//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_so_pay
    {
        public decimal so_id { get; set; }
        public string pay_type { get; set; }
        public string action { get; set; }
        public string curr_id { get; set; }
        public decimal amount { get; set; }
        public string ref_id { get; set; }
        public string result { get; set; }
        public string auth_code { get; set; }
        public string remark { get; set; }
        public System.DateTime update_date { get; set; }
    }
}
