//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_so_reship_prod
    {
        public decimal so_id { get; set; }
        public byte reship_line { get; set; }
        public int prod_id { get; set; }
        public short qty { get; set; }
    }
}
