//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_so_info
    {
        public decimal so_id { get; set; }
        public string pay_type { get; set; }
        public string pay_card_num { get; set; }
        public string person_id { get; set; }
        public string referrer { get; set; }
        public string entry_page { get; set; }
        public System.DateTime entry_date { get; set; }
        public string source { get; set; }
        public string source_remark { get; set; }
        public string user_agent { get; set; }
        public string ip { get; set; }
    }
}
