//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_pay_table
    {
        public System.DateTime updateDate { get; set; }
        public string queryString { get; set; }
        public string formString { get; set; }
        public string headerString { get; set; }
    }
}
